export default (ActiveEffect) => class extends ActiveEffect {
    /** @override */
    prepareDerivedData() {
        super.prepareDerivedData();

        if (!this.origin
            || this.statuses.has(CONFIG.specialStatusEffects.MAGICAL)
            || this.statuses.has(CONFIG.specialStatusEffects.CONCENTRATING)) {
            return;
        }

        const type = foundry.utils.parseUuid(this.origin).type;

        if (type !== "ActiveEffect" && type !== "Item") {
            return;
        }

        if (this.flags.dnd5e?.spellLevel !== undefined || this.name.match(MAGICAL_EFFECTS)) {
            this.statuses.add(CONFIG.specialStatusEffects.MAGICAL);
        }
    }
};

/** @type {RegExp} */
const MAGICAL_EFFECTS = new RegExp(`^${Array.from(new Set([
    "Aid", "Level 2: +5 Max HP", "Level 3: +10 Max HP", "Level 4: +15 Max HP", "Level 5: +20 Max HP", "Level 6: +25 Max HP", "Level 7: +30 Max HP", "Level 8: +35 Max HP", "Level 9: +40 Max HP",
    "Animal Friendship", "Charmed",
    "Animal Messenger", "Carrying Message",
    "Animal Shapes",
    "Animate Objects",
    "Antipathy/Sympathy", "Antipathy", "Sympathy", "Charmed", "Frightened",
    "Astral Projection", "Suspended Animation",
    "Bane",
    "Banishment", "Banished",
    "Barkskin", "Bark-like Skin",
    "Beacon of Hope", "Hopeful",
    "Beast Bond",
    "Beast Sense",
    "Bestow Curse", "Cursed Actions", "Cursed Attacks", "Cursed Charisma", "Cursed Constitution", "Cursed Dexterity", "Cursed Intelligence", "Cursed Strength", "Cursed Wisdom", "Cursed Charisma", "Cursed Resilience",
    "Blade of Disaster",
    "Bless", "Blessed",
    "Blindness/Deafness", "Blindness", "Deafness",
    "Booming Blade", "Booming Energy",
    "Catnap",
    "Cause Fear",
    "Charm Monster", "Charmed",
    "Charm Person", "Charmed",
    "Compelled Duel", "Compelled",
    "Compulsion", "Charmed",
    "Contagion", "Infected (Charisma)", "Infected (Constitution)", "Infected (Dexterity)", "Infected (Intelligence)", "Infected (Strength)", "Infected (Wisdom)",
    "Crown of Madness", "Spectral Crown",
    "Crown of Stars",
    "Darkvision",
    "Death Ward", "Protection from Death",
    "Dispel Evil and Good", "Dispelling Evil and Good",
    "Dominate Beast",
    "Dominate Monster",
    "Dominate Person", "Dominated",
    "Dragon's Breath", "Dragon’s Breath",
    "Dream", "Trance State",
    "Earthbind",
    "Elemental Bane",
    "Enemies Abound",
    "Enervation",
    "Enhance Ability", "Enhanced Charisma", "Enhanced Dexterity", "Enhanced Intelligence", "Enhanced Strength", "Enhanced Wisdom",
    "Enlarge/Reduce", "Enlarged", "Reduced",
    "Enthrall", "Distracted",
    "Eyebite", "Asleep", "Panicked", "Sickend",
    "Fast Friends",
    "Feather Fall",
    "Feign Death", "Cataleptic",
    "Flame Blade",
    "Flesh to Stone", "Turning to Stone", "Unable to Move",
    "Fly", "Flight",
    "Foresight",
    "Fortune's Favor", "Fortune’s Favor",
    "Freedom of Movement", "Unrestricted Movement",
    "Friends", "Charmed",
    "Gaseous Form",
    "Geas", "Under Orders",
    "Gift of Alacrity",
    "Greater Invisibility", "Invisible",
    "Guidance", "Acrobatic Guidance", "Animal Handling Guidance", "Arcana Guidance", "Athletic Guidance", "Deception Guidance", "History Guidance", "Insight Guidance", "Investigation Guidance", "Intimidation Guidance", "Medicine Guidance", "Nature Guidance", "Persuasion Guidance", "Perception Guidance", "Performance Guidance", "Religion Guidance", "Sleight of Hand Guidance", "Stealth Guidance", "Survival Guidance",
    "Guiding Bolt",
    "Haste", "Hasted", "Lethargy",
    "Heat Metal", "Heated Metal",
    "Heroism", "Bravery",
    "Hex", "Hexed Charisma", "Hexed Constitution", "Hexed Dexterity", "Hexed Intelligence", "Hexed Strength", "Hexed Wisdom",
    "Hold Monster", "Paralyzed",
    "Hold Person", "Paralyzed",
    "Holy Weapon",
    "Hunter's Mark", "Hunter’s Mark",
    "Immolation",
    "Imprisonment", "Chaining", "Slumber", "Burial", "Hedged Prison", "Minimus Containment",
    "Incite Greed",
    "Invisibility", "Invisible",
    "Jump",
    "Levitate", "Levitating",
    "Longstrider",
    "Mage Armor",
    "Magic Stone",
    "Mass Polymorph",
    "Mass Suggestion", "Charmed",
    "Maximilian's Earthen Grasp", "Maximilian’s Earthen Grasp",
    "Maze", "Banished",
    "Mental Prison",
    "Mind Blank", "Mind Blanked",
    "Mind Spike", "Spiked",
    "Modify Memory", "Memory Modification",
    "Mordenkainen's Sword", "Mordenkainen’s Sword",
    "Motivational Speech",
    "Nondetection", "Hidden from Divination",
    "Nystul's Magic Aura", "Nystul’s Magic Aura", "Masked",
    "Otiluke's Resilient Sphere", "Otiluke’s Resilient Sphere", "Enclosed in Sphere",
    "Otto's Irresistible Dance", "Otto’s Irresistible Dance", "Irresistible Dance", "Short Dance",
    "Pass without Trace", "Concealed",
    "Phantasmal Killer", "Fears Manifested",
    "Planar Binding", "Bound to Service",
    "Polymorph",
    "Produce Flame",
    "Protection from Energy", "Acid Protection", "Cold Protection", "Fire Protection", "Lightning Protection", "Thunder Protection",
    "Protection from Evil and Good", "Protected",
    "Protection from Poison", "Poison Protection",
    "Rary's Telepathic Bond", "Rary’s Telepathic Bond", "Bonded Telepathy",
    "Ray of Enfeeblement", "Brief Enfeeblement", "Enervated",
    "Reality Break",
    "Regenerate", "Regenerating",
    "Resistance", "Acid Protection", "Bludgeoning Protection", "Cold Protection", "Fire Protection", "Lightning Protection", "Necrotic Protection", "Piercing Protection", "Poison Protection", "Radiant Protection", "Slashing Protection", "Thunder Protection",
    "Sanctuary", "Warded",
    "Seeming", "Changed Appearance",
    "Sequester", "Sequestered",
    "Shield of Faith", "Shimmering Field",
    "Shining Smite", "Shining",
    "Skill Empowerment",
    "Slow", "Slowed",
    "Stoneskin",
    "Suggestion", "Pursuing Suggestion",
    "Tasha's Hideous Laughter", "Tasha’s Hideous Laughter", "Uncontrollable Laughter",
    "Tasha's Mind Whip", "Tasha’s Mind Whip",
    "Telekinesis",
    "Telepathy", "Telepathically Linked",
    "Temporal Shunt",
    "Tether Essence",
    "Tongues", "Universal Communication",
    "True Polymorph",
    "Vampiric Touch",
    "Warding Bond", "Bonded",
    "Water Breathing",
    "Water Walk", "Water Walking",
    "Wind Walk", "Cloud Form",
    "Witch Bolt", "Sustained Lightning",
])).sort().map(RegExp.escape).join("|")}$`, "i");

globalThis.MAGICAL_EFFECTS = MAGICAL_EFFECTS;
